name: MyAutoTask  # 任务名字

on:
  workflow_dispatch: # 重点：这行能让你在网页上点按钮手动触发，调试必备
  schedule:
    - cron: '0 22 * * *' # 每天北京时间早上6点跑（UTC 22:00）

jobs:
  build:
    runs-on: ubuntu-latest # 给你的免费服务器系统
    steps:
      - uses: actions/checkout@v3 # 第一步：把你的代码下载到这台服务器上

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # 第二步：安装 Python 环境

      - name: Install Chinese Fonts (Full Support)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-microhei fonts-wqy-zenhei xfonts-wqy

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run my script
        env:
          # 格式是：自定义环境变量名: ${{ secrets.你刚才填的Name }}
          ACCOUNT: ${{ secrets.ACCOUNT }} 
          PASSWORD: ${{ secrets.PASSWORD }} 
        run: python main.py

      - name: Upload Screenshots # 这一步是关键
        if: always() # 确保即使脚本报错了，也要上传截图
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "**/*.png" # 暴力搜索所有子目录下的 png
          retention-days: 5       # 图片保存天数
